package org.lqfb.ui.vaadin.member;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;

public class MemberProfile extends CustomComponent {

	@AutoGenerated
	private FormLayout mainLayout;
	@AutoGenerated
	private TextField textField_10;
	@AutoGenerated
	private TextField textField_9;
	@AutoGenerated
	private TextField textField_8;
	@AutoGenerated
	private TextField textField_7;
	@AutoGenerated
	private TextField textField_6;
	@AutoGenerated
	private TextField textField_5;
	@AutoGenerated
	private TextField textField_4;
	@AutoGenerated
	private TextField textField_3;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private TextField textField_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MemberProfile() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private FormLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new FormLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setCaption("Name");
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		textField_1.setSecret(false);
		mainLayout.addComponent(textField_1);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setCaption("Realname");
		textField_2.setImmediate(false);
		textField_2.setWidth("-1px");
		textField_2.setHeight("-1px");
		textField_2.setSecret(false);
		mainLayout.addComponent(textField_2);
		
		// textField_3
		textField_3 = new TextField();
		textField_3.setCaption("eMail");
		textField_3.setImmediate(false);
		textField_3.setWidth("-1px");
		textField_3.setHeight("-1px");
		textField_3.setSecret(false);
		mainLayout.addComponent(textField_3);
		
		// textField_4
		textField_4 = new TextField();
		textField_4.setCaption("Jabber (XMPP)");
		textField_4.setImmediate(false);
		textField_4.setWidth("-1px");
		textField_4.setHeight("-1px");
		textField_4.setSecret(false);
		mainLayout.addComponent(textField_4);
		
		// textField_5
		textField_5 = new TextField();
		textField_5.setCaption("Website");
		textField_5.setImmediate(false);
		textField_5.setWidth("-1px");
		textField_5.setHeight("-1px");
		textField_5.setSecret(false);
		mainLayout.addComponent(textField_5);
		
		// textField_6
		textField_6 = new TextField();
		textField_6.setCaption("Telefon");
		textField_6.setImmediate(false);
		textField_6.setWidth("-1px");
		textField_6.setHeight("-1px");
		textField_6.setSecret(false);
		mainLayout.addComponent(textField_6);
		
		// textField_7
		textField_7 = new TextField();
		textField_7.setCaption("Beruf");
		textField_7.setImmediate(false);
		textField_7.setWidth("-1px");
		textField_7.setHeight("-1px");
		textField_7.setSecret(false);
		mainLayout.addComponent(textField_7);
		
		// textField_8
		textField_8 = new TextField();
		textField_8.setCaption("Organisationseinheit");
		textField_8.setImmediate(false);
		textField_8.setWidth("-1px");
		textField_8.setHeight("-1px");
		textField_8.setSecret(false);
		mainLayout.addComponent(textField_8);
		
		// textField_9
		textField_9 = new TextField();
		textField_9.setCaption("Mitgliedschaften");
		textField_9.setImmediate(false);
		textField_9.setWidth("-1px");
		textField_9.setHeight("-1px");
		textField_9.setSecret(false);
		mainLayout.addComponent(textField_9);
		
		// textField_10
		textField_10 = new TextField();
		textField_10.setCaption("€mter");
		textField_10.setImmediate(false);
		textField_10.setWidth("-1px");
		textField_10.setHeight("-1px");
		textField_10.setSecret(false);
		mainLayout.addComponent(textField_10);
		
		return mainLayout;
	}

}
